 get:
    requestBody: {}
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        evetsResponse:
                            value: "    {\r\n        \"date\": \"2022-08-08 19:00\",\r\n        \"id\": 1,\r\n        \"location\": \"Aedevahe talu, Kursi küla, Harjumaa\",\r\n        \"name\": \"Magnus' Among Us themed Birthday Party\",\r\n        \"price\": \"16.50\"\r\n    },\r\n    {\r\n        \"date\": \"2022-03-25 16:00\",\r\n        \"id\": 2,\r\n        \"location\": \"Raekoja plats\",\r\n        \"name\": \"Joe Nuts' Public Execution\",\r\n        \"price\": \"6.99\"\r\n    },\r\n    {\r\n        \"date\": \"2022-06-01 14:00\",\r\n        \"id\": 3,\r\n        \"location\": \"Saku Suurhall\",\r\n        \"name\": \"Eminmen Concert\",\r\n        \"price\": \"0\"\r\n    }"
            description: get events
    summary: get events
    description: get all events 